name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Generate Makefiles
      run: ./ogl/premake/premake5 gmake
      
    - name: make
      run: make CC=gcc
      
    - uses: actions/upload-artifact@v2
      with:
        name: RayXViewer Build
        path: bin/Debug-linux-x86/RayXViewer
